sudo: false
language: java
jdk:
- oraclejdk8
install:
- "./gradlew --version"
script:
- "./gradlew --continue build"
after_success:
- git status
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X}
  != X ]; then ./gradlew release; fi
cache:
  directories:
  - "$HOME/.gradle"
env:
  secure: "mW5FO4awa2BAqL6yr//i5Db6VgngTArlc7YYOurCk1oOZ/nKdPQnUTJr5o7Uuf+PusJDn3/oki0MPgLKcWYsLrlR1xLTREGHo7mEw0oA8BbNyj8ZJPLeSq6REsKGisqthsJFcFsBTmwae3aQ03es5ypPDIXeE1TSAWxVz5f1wZg8jYP64EAVEvIGKfu21MPxMTJ7oKV9VqKuoUkISOfh8pxzVzadmrRZykB70FV1K3s6ijHCoajKcObunF0gnupfAbypPYUMQaEjsotYD/N5R9CO12azQy5lNM3JQK9TvN3oFA/hoBEMHliKdqyB29qJk7tUyyZ7wMVqnkV8mE4SLfolRx+ybELqQ0/CcUmgspyO3kFyoR9IhS7KohOGjXlD9VebpyfYHXT1d+7lu0IWWJv7ZHNVqRcimHWznwD9thPXkgwJYgLwK8YA4/Tazc27DzherSS7TsNSoHUAk84ePM6RfUeGGAzmZPnEU6/TB1kC8YSpq3FCPHIU77DO3BviGKvwSk+0Hzs3FvwEOdB+8mRKGQtjWjNcqwIAqzDXgNrHAVEaGKmWV7viLfJPWWVu09RdW6vPSfmQ7tt7KnX4tXX975A8aLh2153W0AMIESB6HzQK8AX1h5CqUyZIj+oy9MBGwDJ9PnBGMqCKAbSCZlRWD7AWM+zleX2oL1gwFho="
